# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BestOne' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BestOne
  pod 'AWSCognito'
  pod ‘AWSCore’
  pod 'SwiftyJSON'
  pod 'AWSCognitoIdentityProvider'
  pod 'Alamofire', '~> 4.4'
  pod 'UICKeyChainStore'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
end

target 'BestOneWatchKitApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BestOneWatchKitApp

end

target 'BestOneWatchKitExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BestOneWatchKitExtension

end

target 'BestOneWidget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BestOneWidget

end
